### ISSUE TITLE
latest kube-aws installs kubelet 1.0.6

### ISSUE THREAD

**Issue by lukemarsden** [coreos/coreos-kubernetes#179]
```
ip-10-0-0-50 ~ # kubelet --version
Kubernetes v1.0.6-release-1.0+388061f
```

Yet e.g. `hyperkube:v1.1.1` is running as a container.

**Comment by aaronlevy** [comment]
Hi @lukemarsden,

The kubelet currently ships with the OS image, so this tool may launch newer master components (where you see `hyperkube:v1.1.1`), while the OS has an earlier versioned kubelet. This is a supported upgrade path, so your master components can be updated prior to the underlying kubelet.

As a side note, the latest CoreOS Alpha image is shipping with a v1.1.2 kubelet. Any new clusters launched using the Alpha channel should see this change. Upgrade documentation for existing clusters launched via the kube-aws tool are still forthcoming.

I'm going to close this issue for now, but please re-open if you have any more questions regarding the versioning.

**Comment by lukemarsden** [comment]
Thanks for the reply @aaronlevy and good to see you at Tectonic summit :)

It's particularly bad because `kubectl version` lies to you (it doesn't report the version of the kubelet). So for example folks trying Flocker on Kubernetes will mysteriously not succeed. Could we document this in the coreos-kubernetes README? I'd be happy to do a PR if you'd be OK with that.

**Comment by aaronlevy** [comment]
Unfortunately, I wasn't at the summit. But I hope my illustrious colleagues were helpful :). Also my github avatar isn't exactly the best for recognition ...

I think that if it caused confusion, it might be worth more clearly documenting. Looking to the near future the plan is to ship the kubelet in a signed image/container so the end-user can explicitly select the version they would like to run rather than relying strictly on the kubelet on the host.

**Comment by phemmer** [comment]
Just curious, but why is the kubelet baked into the AMI?
I can understand if the reason is so you don't have to go out to the internet to install it at boot, but what if the kubelet is downloaded from the master? This puts reliance on the master being available, but this seems acceptable as if the master is unavailable, the kubelet will be useless anyway.
By doing this, we can ensure that no matter the AMI version, the kublet version will always match the master's version.

**Comment by xied75** [comment]
https://github.com/coreos/bugs/issues/978
Might help, this is still open there.
