### ISSUE TITLE
Cloud Configs templates for AWS

### ISSUE THREAD

**Issue by sachingharge** [coreos/coreos-kubernetes#202]
Hi Team,

It would be good if cloud config template (YMAL) files provided for CoreOS AWS setup similar like below.
https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos

It would be really helpful for custom cloudformation template. In cloudformation template, I am trying to use latest stable version of CoreOS 835.9.0 and Kubernetes v1.1.3 version however facing some issues while communicating between containers (I think because of kube-proxy but not sure how to troubleshoot that)
One service is exposed via ClusterIP and one with Loadbalancer (using ELB). It is been working with cluster setup (Kubernetes stable v1.0.7 on EC2 powered by CoreOS 766.5.0)

Another questions, why do need to use alpha release in template? Can't we use stable version of CoreOS?

Also please confirm if below previous points are resolved till Kubernetes v1.1.3
1. AWS Hard coded VPC name (kubernetes-vpc): this seems to be fixed.
2. AWS multi AZ for nodes and creation of external loadbalancer using ELB: I think this is also fixed, please confirm?

Can you please let me know your inputs on this and also please review below cloud configs for Kube master and Node?

Also do we need to run kube-proxy on master node? I think we don't need to run, please confirm?
It should be run only on Node.

https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/artifacts/manifests/controller/kube-proxy.yaml

Master: https://github.com/sachingharge/automation-scripts/blob/master/cloud-config-master.yaml
Node: https://github.com/sachingharge/automation-scripts/blob/master/cloud-config-node.yaml

Cloudformation template link where above mentioned cloud config is used:
https://github.com/sachingharge/automation-scripts/blob/master/kube-cloudformation.template

Thanks in advance!

**Comment by sachingharge** [comment]
Just to add, I am seeing below error in systemd logs for kube-proxy on nodes:

Dec 14 17:40:48 ip-10-19-2-116.us-west-1.compute.internal kube-proxy[980]: E1214 17:40:48.308099     980 server.go:357] Not trying iptables proxy: can't get Node "ip-10-19-2-116.us-west-1.compute.internal": node "ip-10-19-2-116.us-west-1.compute.internal" not found

Any idea why?


Systemd file for kube-proxy
cat /etc/systemd/system/kube-proxy.service
[Unit]
Description=Kubernetes Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
Requires=hostname-override.service
After=hostname-override.service

[Service]
ExecStartPre=-/usr/bin/mkdir -p /opt/bin
ExecStartPre=/usr/bin/curl -L -o /opt/bin/kube-proxy -z /opt/bin/kube-proxy https://storage.googleapis.com/kubernetes-release/release/v1.1.3/bin/linux/amd64/kube-proxy
ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-proxy
ExecStart=/opt/bin/kube-proxy \
--master=http://10.19.1.238:8080 \
Restart=always
RestartSec=10

**Comment by xied75** [comment]
@sachingharge Not really sure what your question is about, but you can certainly provider your own aws cloudformation template as however you want it; you can also provider your own CoreOS yaml files too.

**Comment by robszumski** [comment]
This repo contains some shell scripts that can be used as user-data for both workers and controllers, located here: https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic

Does that help you?

**Comment by aaronlevy** [comment]
> It would be good if cloud config template (YMAL) files provided for CoreOS AWS setup

If you wish to create your own custom cloud-configs, the assets we use (the cloud-configs for controller/worker and all templates) are here: https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws/artifacts 

These are meant to be used via the kube-aws tool, but can be modified / used directly with a little bit of customization.

We also have generic cloud-configs (as bash scripts) here: https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic

Note that the generic scripts are not AWS specific, and expect certain SSL assets to be located in /etc/kubernetes/ssl -- so this will also take some manual changes.

> Can't we use stable version of CoreOS?

The Kubelet binary is currently only available in the alpha and beta channels. If you wish to use the stable channel, you will need to download the kubelet to the host, as it will not be part of the OS image.

> AWS Hard coded VPC name (kubernetes-vpc)

It looks like this was fixed as of v1.1.0: https://github.com/kubernetes/kubernetes/pull/13467

> AWS multi AZ for nodes and creation of external loadbalancer using ELB

I'm a little unclear on exactly what you're asking. As far as Kubernetes you can launch nodes in different AZs and have them join your cluster, and you can also create external loadbalancers using ELB.

As for as the kube-aws tool in this repository, it currently assumes nodes are being launched in a single AZ.

> Also do we need to run kube-proxy on master node?

In our documentation / examples we run the kube-proxy on all nodes (including master). This is so that requests to kubernetes services on any node can be properly routed to the endpoints / pods. If master nodes remain unschedulable / do not need to handle any service routing, you could get away with not running a kube-proxy, but in general I wouldn't suggest this unless you're sure you don't need it.

As far as the template links that you provide, these to not look like they were generated from our documentation / tools. I would suggest taking a look at our [step-by-step getting started guides](https://coreos.com/kubernetes/docs/latest/getting-started.html)

**Comment by somejfn** [comment]
"AWS multi AZ for nodes and creation of external loadbalancer using ELB"

I would interpret this as a feature request so that the ELB created via
cloud provider integration would support multiple vPC segments and
ultimately load balance PODs from an RC across AZs.  But to make sure PODs
are actually deployed across AZs we'd need to anti-affinity rules (maybe an
extension of node selectors ?)

**Comment by aaronlevy** [comment]
@somejfn there is some upstream work to support this type of use case on AWS ("federation-lite"): https://github.com/kubernetes/kubernetes/issues/17059

Until then, it would require using node-selectors and a replication controller for each set of availability zones you wanted to keep pods running in. This is because the replication controllers currently have no ability to load-balancing across node selectors.

**Comment by aaronlevy** [comment]
@sachingharge I'm going to close this issue for now, feel free to reopen if the information above did not answer your questions.
