### ISSUE TITLE
kubernetes deploy-master doesn't suggest creating /srv/ on coreos

### ISSUE THREAD

**Issue by robszumski** [coreos/coreos-kubernetes#203]
Moving issue to correct location: @mischief.

Do you have any more info you could share?

**Comment by omkensey** [comment]
I was just talking with @ecnahc515 about this, or at least a closely related issue, on Friday.  Our documentation does not explain at all why the manifests for the controller-manager and scheduler go in /srv/kubernetes/manifests rather than in /etc/kubernetes/manifests like the ones for apiserver, proxy, and podmaster.  It turns out there *is* a reason, specifically that that ensures their startup is controlled by the podmaster, but it's easy to overlook the difference in directory names when setting the environment up under time pressure.

I'm working on a PR to resolve that issue by explaining the difference more explicitly, which will also resolve the issue named here.  Should I open a new issue to reference, or keep discussion of my PR here?

Going further, am I correct in assuming that the directory names are more or less arbitrary and controlled entirely by the arguments used to start up kubelet and podmaster?  In that case I would recommend naming them more distinctively -- maybe by using a subdirectory?  /etc/kubernetes/manifests is probably OK but the other should ideally call out more explicitly that it's for podmaster-controlled singleton services in its name.

**Comment by robszumski** [comment]
I think keeping the discussion here is fine. I don't see this being much more than a sentence that explains a bit more about what the podmaster does. Here's what we currently have:

> The kube-podmaster is responsible for implementing master-election for the kube-controller-manager and kube-scheduler. Because these services modify the cluster state, we only want to have one actor making modifications at a time.

> In a single-master deployment, the kube-podmaster will simply run the kube-scheduler and kube-controller-manager on the current node. In a multi-master deployment, the kube-podmaster will be responsible for starting a new instance of the Kubernetes components in the case of a machine dying.

It seems like it lacks just a few facts:

1. Role of `/srv/kubernetes/`. Might need to tell folks they have to create it.
2. Role of `/etc/kubernetes/`.
3. The podmaster controls things by moving these files around, hence they need to be in `/srv` in the beginning.
4. Use the single node as a way to explain this:

> For example, in a single-master deployment, the kube-podmaster will simply run the kube-scheduler and kube-controller-manager on the current node. It does this by copying the two YAML files from `/srv/kubernetes/manifests` to `/etc/kubernetes/manifests`.
--new paragraph--
> In a multi-master deployment, ...<snip>... machine dying. When a machine dies, the podmaster uses etcd to perform a master-election, and the elected machine moves manifests from `/srv/kubernetes/manifests` to `/etc/kubernetes/manifests`.

**Comment by aaronlevy** [comment]
The /srv location was used mostly because that's what it was upstream (http://kubernetes.io/v1.1/docs/admin/high-availability/podmaster.yaml), but yes it is arbitrary.

Also, there is a target for this to go away by v1.2 (tools will master elect themselves rather than rely on podmaster) -- so I'd lean toward not changing location for now just for consistency sake.
