### ISSUE TITLE
Connection Refused when setting up kubernetes

### ISSUE THREAD

**Issue by ramonrue** [coreos/coreos-kubernetes#215]
Hi,
I'm currently trying out CoreOS and wanted to set up Kubernetes. I noticed following situation:
When setting up kubernetes / kubelet with the official documents (https://coreos.com/kubernetes/docs/latest/deploy-master.html) following error occurs after starting the kubelet.service with systemd:

```shell
curl http://127.0.0.1:8080/version
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```
Doing a docker ps gives following:
```shell
docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS               NAMES
6001dfaf2dd9        gcr.io/google_containers/podmaster:1.1      "/podmaster --etcd-se"   12 minutes ago      Up 12 minutes                           k8s_controller-manager-elector.1e0f60d1_kube-podmaster-192.168.1.31_kube-system_f3587bb6242675559714311a0963fda7_ab3a4c48
236ede47f54c        gcr.io/google_containers/hyperkube:v1.1.2   "/hyperkube proxy --m"   15 minutes ago      Up 15 minutes                           k8s_kube-proxy.9b9c389f_kube-proxy-192.168.1.31_kube-system_a1462c3b7ea1599738afa9a7acd567ca_f7272aca
9486367c23e8        gcr.io/google_containers/podmaster:1.1      "/podmaster '--etcd-s"   15 minutes ago      Up 15 minutes                           k8s_scheduler-elector.4fc358cb_kube-podmaster-192.168.1.31_kube-system_f3587bb6242675559714311a0963fda7_3da994cd
4d4cd35b989f        gcr.io/google_containers/pause:0.8.0        "/pause"                 15 minutes ago      Up 15 minutes                           k8s_POD.e4cc795_kube-apiserver-192.168.1.31_kube-system_158edf8c7932bc578f61ef742415b674_67ab39e4
d2ffba779ec1        gcr.io/google_containers/pause:0.8.0        "/pause"                 15 minutes ago      Up 15 minutes                           k8s_POD.e4cc795_kube-proxy-192.168.1.31_kube-system_a1462c3b7ea1599738afa9a7acd567ca_e48ef93a
11fc8e6181ce        gcr.io/google_containers/pause:0.8.0        "/pause"                 15 minutes ago      Up 15 minutes                           k8s_POD.e4cc795_kube-podmaster-192.168.1.31_kube-system_f3587bb6242675559714311a0963fda7_20b0086b
```

Am I missing something or should there be a port opened (8080) at the API-Container? 
I replaced all variables that are written in the document:
* ${ETCD_ENDPOINTS} - 127.0.0.1:2379 (Yes, etcd is up and running and working)
* ${DNS_SERVICE_IP} - 192.168.1.1 - My DNS Server running in that network
* ${ADVERTISE_IP} - 192.168.1.31
* ${SERVICE_IP_RANGE} - 192.168.1.0/24

Any help would be greatly appreciated.

**Comment by aaronlevy** [comment]
It looks like the api-server might not be running.

The api-server on the master node is self-bootstrapped by the kubelet. In the kubelet.service unit it should have a `--config=` flag which points to a directory to look for static pod manifests (one of which is the api-server).

You would normally see the kubelet start, and it complain about not being able to reach the api-server on 127.0.0.1:8080 (because none is running yet). Then it will start an api-server locally after it picks up the static-pod config from a location on disk (`--config` location).

Because it looks like no api-server is running, there are a couple places to check:

- Is the api-server starting / failing for some reason? `docker ps -a` then `docker logs <container id>` of thrashing container.
- Is the kubelet.service logging anything about failing to start the api-server? Can also increase log verbosity with `--v=4` on the kubelet.
- If logs don't have anything intersting, it very likely is due to mal-formed yaml in the pod manifest itself (default location `/etc/kubernetes/manifests/kube-apiserver.yaml`). The kubelet can silently ignore the file if it is not able to properly parse it.

**Comment by ramonrue** [comment]
Got it!
The docker logs for the container were:
```shell
I1222 07:43:53.111244       1 plugins.go:71] No cloud provider specified.
I1222 07:43:53.364709       1 master.go:368] Node port range unspecified. Defaulting to 30000-32767.
E1222 07:43:53.393437       1 cacher.go:149] unexpected ListAndWatch error: pkg/storage/cacher.go:115: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]
E1222 07:43:53.393613       1 cacher.go:149] unexpected ListAndWatch error: pkg/storage/cacher.go:115: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]
E1222 07:43:53.394255       1 cacher.go:149] unexpected ListAndWatch error: pkg/storage/cacher.go:115: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]
[restful] 2015/12/22 07:43:53 log.go:30: [restful/swagger] listing is available at https://192.168.1.31:443/swaggerapi/
[restful] 2015/12/22 07:43:53 log.go:30: [restful/swagger] https://192.168.1.31:443/swaggerui/ is mapped to folder /swagger-ui/
E1222 07:43:53.418894       1 cacher.go:149] unexpected ListAndWatch error: pkg/storage/cacher.go:115: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]
E1222 07:43:53.419182       1 cacher.go:149] unexpected ListAndWatch error: pkg/storage/cacher.go:115: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]
E1222 07:43:53.419639       1 cacher.go:149] unexpected ListAndWatch error: pkg/storage/cacher.go:115: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]
F1222 07:43:53.440214       1 controller.go:80] Unable to perform initial IP allocation check: unable to refresh the service IP block: 501: All the given peers are not reachable (failed to propose on members [172.17.0.1:2379] twice [last error: Get 172.17.0.1:2379/v2/keys/registry/ranges/serviceips?quorum=false&recursive=false&sorted=false: unsupported protocol scheme ""]) [0]
```

Like I said, I adopted all files from the how-to. In the file ```/etc/kubernetes/manifests/kube-apiserver.yml``` I entered an incorrect IP-address. 
At the beginning, I had ``` - --etcd-servers=127.0.0.1:2379``` which was obviously, in a docker container, that it won't work. I found that and corrected it to ``` - --etcd-servers=172.17.0.1:2379``` which didn't work either (The log file above is of that entry). 
The correct entry is  ```- --etcd-servers=http://172.17.0.1:2379```. Now the container is up & running. 

```shell
curl http://127.0.0.1:8080/version
{
  "major": "1",
  "minor": "1",
  "gitVersion": "v1.1.2",
  "gitCommit": "3085895b8a70a3d985e9320a098e74f545546171",
  "gitTreeState": "clean"
}
```
Thank you for your help!

**Comment by ramachittala** [comment]
Hi 
Iam starting the following error is occurd.

localhost ~ # systemctl status kube-apiserver.service
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; static; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-02-07 14:47:23 UTC; 6s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 10596 ExecStartPre=/usr/bin/curl -L -o /opt/bin/kube-apiserver -z /opt/bin/kube-apiserver https://storage.googleapis.com/kubernetes-
  Process: 10592 ExecStartPre=/usr/bin/mkdir -p /opt/bin (code=exited, status=0/SUCCESS)
 Main PID: 5073 (code=exited, status=203/EXEC)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/kube-apiserver.service

Feb 07 14:47:23 localhost systemd[1]: kube-apiserver.service: Control process exited, code=exited status=6
Feb 07 14:47:23 localhost systemd[1]: Failed to start Kubernetes API Server.
Feb 07 14:47:23 localhost systemd[1]: kube-apiserver.service: Unit entered failed state.
Feb 07 14:47:23 localhost systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.

This is error log:
#journalctl -xe

-- The start-up result is done.
Feb 07 14:47:34 localhost kubelet-wrapper[10675]: KUBELET_VERSION environment variable is deprecated, please use KUBELET_IMAGE_TAG instead
Feb 07 14:47:34 localhost kubelet-wrapper[10675]: + exec /usr/bin/rkt run --trust-keys-from-https --volume etc-kubernetes,kind=host,source=/etc
Feb 07 14:47:35 localhost kubelet-wrapper[10675]: run: discovery failed
Feb 07 14:47:35 localhost systemd[1]: kubelet.service: Main process exited, code=exited, status=254/n/a
Feb 07 14:47:35 localhost systemd[1]: kubelet.service: Unit entered failed state.
Feb 07 14:47:35 localhost systemd[1]: kubelet.service: Failed with result 'exit-code'.


Please help.

**Comment by Swivelgames** [comment]
@ramachittala It's a little late, but if you're running into a problem I'd advise creating a new issue ticket. There isn't much incentive to peruse closed issues for new comments, especially if they're not made by the op. You may get mixed results on various repos when replying to old / closed issues.
