### ISSUE TITLE
kube-aws: render reproducible asset for cluster

### ISSUE THREAD

**Issue by philips** [coreos/coreos-kubernetes#218]
A user told me yesterday that they don't want to use kube-aws because there is no way for them to check the result of a kube-aws run into git. Essentially they wanted the kube-aws tool to render the autoscale groups, cloud-configs, etc to disk and then be able to run the `aws` CLI or kube-aws tool over those assets to deploy. This way they can always restore their infra without worrying about change in behaviour of the kube-aws in future versions.

**Comment by sym3tri** [comment]
This came up during #hackday too. I think a multi-step process would be ideal, with the 2nd step being optional. This would also give users a chance to make slight modifications if needed instead of being too much of a black-box.

- step 1: write assets to disk
- step 2: use assets from disk to deploy everything.

**Comment by joeatwork** [comment]
This also helps our "use the simple stuff to learn the complicated stuff" UX - in general, the more manifests we can leave for folks to read (without *requiring* anybody to read them) the better!

**Comment by colhom** [comment]
work in progress #240

**Comment by colhom** [comment]
This functionality has landed in master. `kube-aws render` now produces TLS assets, userdata and stack templates as files. `kube-aws up --export` will dump the stack template json to file as well. This exported file is the "complete description" of your cloudformation stack (no remote URL references).
