### ISSUE TITLE
resize cluster without destroying it first

### ISSUE THREAD

**Issue by adamfeuer** [coreos/coreos-kubernetes#230]
We would like to use `kube-aws` to resize the cluster without first destroying it - for instance, to add more worker nodes by updating the CloudFormation template.

We tried rendering the CloudFormation template and using the `awscli` tool to update the stack, but that didn't work because the SSL cert contents are not rendered into the template when using `kube-aws render`. 

We want to be able to add and remove worker nodes dynamically, and this feature would make it a lot easier.

I'm willing to contribute PR for this if you think this would be helpful.

**Comment by colhom** [comment]
@adamfeuer we are currently working on reproducible cluster assets (#218), which would make dropping new components into an existing CF template much easier.

**Comment by adamfeuer** [comment]
@colhom Well, I'd prefer not to alter the CF template directly - it defeats the purpose of having a higher-level tool like `kube-aws`. But if `kube-aws` would do the altering, then it would help me. Is there some way we can help this effort...?

**Comment by colhom** [comment]
The general flow that I'm envisioning would be:

````
kube-aws render --output ./assets.tgz

#create cluster
kube-aws up ./assets.tgz

#destroy cluster
kube-aws destroy ./assets.tgz

#scale cluster
kube-aws scale ./assets.tgz -worker-count N -controller-count N

```

**Comment by adamfeuer** [comment]
@colhom That flow would work for me. Ideally the assets could be either a tgz or a directory, in case I need to use [BlackBox](https://github.com/StackExchange/blackbox) to secure the files.

**Comment by xied75** [comment]
@adamfeuer If all you want is increase or decrease the number of worker nodes, I think you missed the design point of kube-aws all together. kube-aws uses an aws cloudformation template which in turn uses aws auto scaling group, and the initial template does not even mention the worker nodes at all, it is the job of asg that create those nodes according to the asg LaunchConfiguration, which owns how the aws instance should be created with correct user-data etc.

So after you have a running cluster, you can do this to increase the nodes (let's say init size=2):
```
aws autoscaling update-auto-scaling-group --auto-scaling-group-name kube1-AutoScaleWorker-41W5TOYL3U6A --desired-capacity 4 --min-size 4 --max-size 4
```

You can also set the min and max to a larger range, so you can also call (let's say min=2 max=8):

```
aws autoscaling set-desired-capacity --auto-scaling-group-name kube1-AutoScaleWorker-41W5TOYL3U6A --desired-capacity 6
```

This does demand aws cli and could be embedded inside kube-aws cli, but I kind of feel it's not really necessary to absorb those at all.

**Comment by adamfeuer** [comment]
Dong Xie,

I can manually scale up as you say. But to scale down, I need to somehow
tell kubernetes which nodes to protect from the scale-down, so that
critical services are not killed. Or I need a tools to figure out which
nodes are empty of services once I scale the services down using kubectl.

I have seen mention of something called a HorizontalNodeScaler that seems
to go along with the HorizontalPodScaler, but haven't figured out how to do
this in Kubernetes or kube-aws.

-adam

**Comment by xied75** [comment]
@adamfeuer I think fundamentally we should only specify a Priority value to RC/Pods so who ever is doing the scale down can take that for consideration, but apparently aws asg has no knowledge about this, or to say aws asg has no knowledge about k8s. Maybe we could define aws asg termination-policy.

But if you have something "critical" which can't tolerant node down time, then how are you going to protect it against aws instance down for whatever reason? Isn't that the reason to have RC and have multiple instances from the beginning?

**Comment by adamfeuer** [comment]
@xied75 My cluster has a large number of workers of different types - lets say w1 (Celery OCR worker), w2 (RabbitMQ server) and w3 (Flower management console). Let's say there are 5x more w1 than w2+w3.

Right now Kubernetes puts all w1+w2+w3 in the same autoscaling group. If I want to reduce the w1 count, but keep w2 and w3 the same, I can't. If I change the ASG numbers, the ASG will randomly kill some nodes, without regard to what's on them.

Maybe the solution is to create a new ASG that only has w1 in it. But right now that isn't easy from inside Kubernetes or kube-aws. Another solution would be to "protect" some nodes (can do that from the AWS CLI) but again not easy to do. 

I would like something that can easily scale the cluster without service interruptions.

Maybe the problem is really inside Kubernetes though - what I want is a HorizontalNodeScaler combined with a HorizontalPodScaler.

**Comment by thomascooper** [comment]
Sorry to drum up an older question but I wanted to get some clarification, hopefully this is the correct place based on its topic.

I am also looking to design a cluster that both has the capability to scale pods horizontally and nodes horizontally. Using kubernetes I feel like i have the pod scaling understood for the most part, and with AWS autoscaling groups I think I can get the node scaling to meet my needs. I am not only looking for traditional scale for peak load, scale back during less load, but also I am looking to continue to grow our infrastructure as new nodes are needed due to overall capacity, I want the infrastructure to scale when resources dictate that its time to grow, so the min/max autoscaling properties will continue to increase over time for each kubernetes cluster.

I feel like out of the box, kube-aws provides the framework for this, but where I am struggling is this, if I want to change the min/max size of the autoscaling group via some config management, I am struggling with how to do that programmatically. We use ansible for most of our aws config management here, and I am struggling with how to build playbook that will work without some manual inspecting of the asg. Here is would i would love to do

1.) Setup cluster.yml (starting with workerCount of 3)
2.) kube-aws up
3.) ansible-playbook k8ns-scale.yml -e 'min_nodes=5 max_nodes=10'
4.) ansible-playbook setup_apps_n_stuff_via_kubernetes.yml

At this point we could tear down our existing infrastructure and build it back up with no issues, on a go forward basis manually we could based on health or alerting manually run: 

ansible-playbook k8ns-scale.yml -e 'min_nodes=8 max_nodes=16' 

Most of this I am currently able to do, the problem I have right now is that in order to awscli or ansible to change the asg, i need to know the exact name of the group, and it appears that with each deploy there is a custom random identified added to each group name:

aws --region us-east-1 autoscaling describe-auto-scaling-groups --auto-scaling-group-names dt-prg-staging-AutoScaleWorker-[RANDOM_ID]

Has anyone found a way to accomplishing something along the lines of what I am doing? I assume one answer would be to move from kube-aws to ansible for provisioning the entire cluster with cloudformation, but I am still new to cloudformation and it feels like that would be a tremendous effort.

Thanks again guys.

**Comment by boj** [comment]
@thomascooper If you haven't gotten around to it yet, one possible solution is to just parse out the RANDOM_ID into an ansible register.

    aws autoscaling describe-auto-scaling-instances | grep AutoScalingGroupName | cut -d : -f 2 | cut -d , -f 1

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.
