### ISSUE TITLE
AWS: Allow specification of a custom AMI

### ISSUE THREAD

**Issue by iameli** [coreos/coreos-kubernetes#247]
This is probably the least fair feature request I've ever made. About fifteen minutes ago, [AWS announced support for encrypted root EBS volumes](https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/). Why don't you guys support that yet? :smiley: 

I might file a separate request for that, but this ticket is a prerequisite: I need to be able to bring up this stack with a custom AMI -- one that's been encrypted using our KMS key. Seems like it'd be sufficient to add an `ami` parameter to the stack template that overrides the built-in CoreOS version selector if present. 

As an added bonus, this would let folks specify newer versions of CoreOS if this repo hasn't merged them in quite yet.

Will probably submit a PR for this in the next couple days if the design of that feature makes sense to everyone.

**Comment by aaronlevy** [comment]
You should be able to modify the AMI in the rendered cloud-formation template to include your custom image. However, I don't think this approach will work well with the core-update engine, as you will be getting OS updates from the upstream AMIs...

**Comment by iameli** [comment]
That seems fine -- in my case I'm not really using a "custom" image, it's just a copy of the CoreOS AMI that has its EBS encrypted with my KMS key. Unless I'm misunderstanding something about the update process, it should work just as well as it does on the upstream AMI.

**Comment by aaronlevy** [comment]
You're right, the update process should just modify bits on disk rather than pull a new AMI in place. So hypothetically this might work (start with your initial encrypted AMI, then receive updates that modify those local bits).

I checked with one of the guys on our OS team, but he hadn't had a chance to look into how the encrypted root volume feature works, so couldn't really say for sure if this would work out-of-box. Feel free to open an issue at https://github.com/coreos/bugs to get more info on that specific functionality.

Still want to keep this open to track the requested feature of "specify custom AMI". 

/cc @colhom any thoughts on this?

**Comment by meonkeys** [comment]
FYI, right now we're using `kube-aws render` then modifying the output before sending to CloudFormation. We are using encrypted root volumes... seems to be working fine.

I'm new to Go, but it sounds like you're interested in a patch so I'll look into work required to specify a custom AMI. If you aren't interested in a patch, just close this issue.

**Comment by aaronlevy** [comment]
The kube-aws tool has been moved to its own top-level directory @ https://github.com/coreos/kube-aws

If this issue still needs to be addressed, please re-open the issue under the new repository.

**Comment by mumoshu** [comment]
FYI, we can now specify custom AMI ID thanks to https://github.com/coreos/kube-aws/pull/14
