### ISSUE TITLE
AWS: Allow a custom version of kubelet/kubernetes

### ISSUE THREAD

**Issue by iameli** [coreos/coreos-kubernetes#248]
I'm not really sure how y'all at CoreOS want to handle this, but at C-SATS we pretty badly needed some fixes that are present in Kubernetes 1.1.4.

So... [I did this](https://github.com/csats/coreos-kubernetes/commit/835e11602b493c64b0579a5e54dcc033c8a3da1f)! Works great, but that commit is probably anti-patterned to how CoreOS is supposed to work.

I think the long-term solution will be to run kubelet in a container, once that's well-supported by Kubernetes. In the meantime, is there a great way to support customization of kubelet version at runtime?

**Comment by aaronlevy** [comment]
The change you made should work fine. It is somewhat of an anti-pattern in that the software you're running would ideally be distributed as a container rather than simply curl'ing it to the host.

The longer term solution you mention (of running the kubelet in a container) is not too far off. This is the tracking issue: https://github.com/coreos/bugs/issues/1051

In short, we are working toward shipping the kubelet (hyperkube) as a container and executing it on the host via rkt. This would allow you to more cleanly update the kubelet version and just have it pull down a new container. Also in that issue are some proposals for how auto-updating / api-driven updates may allow a simpler upgrade path.

Any feedback on the proposal / direction is always welcome, but at minimum we should have the ability to run custom kubelet version as a container fairly soon.

**Comment by iameli** [comment]
Thanks a ton, that's super helpful. I'll keep my kludge in place until coreos/bugs#1051 gets figured out one way or another. Feel free to either close this ticket in favor of that one or keep it open for reference until it lands.

**Comment by aaronlevy** [comment]
The [kubelet-wrapper](https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html) was introduced in: https://github.com/coreos/coreos-kubernetes/pull/276 so you should now be able to specify custom versions of the kubelet.
