### ISSUE TITLE
Heapster not finding kubelets

### ISSUE THREAD

**Issue by tspecht** [coreos/coreos-kubernetes#293]
Hey guys,

I just used the CF template from the website to spin-up a K8 cluster on AWS and it worked flawless. Then I installed heapster on my cluster but unfortunately it isn't able to find the the kubelets to extract the data. I saw that one issue that was fixed end of last year where port 10250 needed to be added to the security group and made sure that this is reflected in the CF template I'm using.

`failed to get stats for container "etcd" in pod "kube-system"/"kube-dns-v9-ggbbp"`

Any ideas on how I could resolve this or at least where to start debugging it?

**Comment by aaronlevy** [comment]
@tspecht What docker version are you running?

**Comment by aaronlevy** [comment]
I'm going to close this due to inactivity. However, just to note, I was wondering about docker version because v1.10 introduced a change to cgroup handling (which resulted in errors similar to what you were seeing). A fix was introduced in the default docker options in CoreOS: https://github.com/coreos/coreos-overlay/pull/1797/files
