### ISSUE TITLE
kube-aws brings up CoreOS machines running alpha

### ISSUE THREAD

**Issue by ericandrewlewis** [coreos/coreos-kubernetes#307]
I notice that this script brings up the CoreOS machines running the alpha version of the OS. 

Is intended for production use?

**Comment by xied75** [comment]
You can specify ReleaseChannel to alpha or beta in the yaml as kubelet is not yet in the stable. But from CoreOS point of view, I suppose only stable is really meant for production?

**Comment by ericandrewlewis** [comment]
Right, and it looks like stable is [not a supported channel](https://github.com/coreos/coreos-kubernetes/blob/32e5b243a0143177f745d8aeae53804f9e8c9b42/multi-node/aws/pkg/cluster/stack_template.go#L57) yet.

Does this mean folks who desire to run Kubernetes in production should not use this installer?

**Comment by robszumski** [comment]
The reason for this is that we were iterating on how the kubelet was going to be shipped in the image, not that the tool isn't designed for production use. We initially started with the kubelet binary shipped in the image, but we're moving away from that approach in favor of a [rkt-based solution](https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html), which is shipping in 962.0.0+. Once this makes its way to beta and stable (currently alpha) the restriction in the kube-aws code will be removed.

Does that make sense?

**Comment by ericandrewlewis** [comment]
That makes sense. 

Should folks use this installer now to try out the future rkt-based solution, but not intend to put it in production until that is in stable? 

Where should a user go to launch Kubernetes into production today? The [CoreOS installation docs](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html#kube-aws-quickstart) will lead users to install the latest release of `kube-aws`, which uses the rkt-based solution.

**Comment by aaronlevy** [comment]
Because the kube-aws code currently targets the alpha release, you would need to make some manual modifications if you wish to run it against a CoreOS-stable release.

* The resulting cloud-formation would need to be updated to use a coreos-stable AMI-ID
* You would need to manually add the [kubelet-wrapper script](  https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html)

Alternatively, our [step-by-step instructions](https://coreos.com/kubernetes/docs/latest/getting-started.html) are a good starting point for deploying production clusters (but the kube-aws tool is easier to get running quickly).

**Comment by aaronlevy** [comment]
Closing issue, but if we can provide additional help, please reopen/let us know.
