### ISSUE TITLE
kubelet-wrapper needs to mount /var/log

### ISSUE THREAD

**Issue by aknuds1** [coreos/coreos-kubernetes#322]
The kubelet-wrapper needs to include /var/log among its mount points, since kubelet puts container logs in /var/log/containers. I've confirmed this by modifying kubelet-wrapper myself.

**Comment by colhom** [comment]
@aknuds1 check out #320 

We are going to ship the logging components as cluster add-ons in the near future, at which point we will have the rkt kubelet host-mount it's container log files. Until then, just add an Environment entry for `RKT_OPTS` in kubelet.service, which defines the addtional mount flags for `/var/log/container`

**Comment by aknuds1** [comment]
OK, cool. Keep me posted. You should've mounted /var/log/containers from the get-go though, as it breaks kubelet.

**Comment by aaronlevy** [comment]
@aknuds1 curious what breaks in the kubelet?

**Comment by aknuds1** [comment]
@aaronlevy As I state in the issue description, Kubelet isn't able to place logs in /var/log/containers, meaning that in turn fluentd can't collect container logs. So basically, the Kubernetes logging stack (Fluentd/Elasticsearch/Kibana) doesn't work as a result.

**Comment by aaronlevy** [comment]
Right. Just wanted to make sure there wasn't some other breakage I was missing.

FWIW, the kubelet is still collecting the logs, but just inside the chroot of the kubelet container (not the host /var/log/containers). So the kubelet should function normally, but you're correct that external logging applications would not have access to this data.

As @chom mentioned, you can add this mount using `Environment=RKT_OPTS=` in the kubelet unit file.

The original intention was to keep the kubelet-wrapper script as a simple starting point, but we may need to add more to the defaults. I'll leave this issue open to track this feature request.

**Comment by MurgaNikolay** [comment]
Hi guys.
How we can mount `/var/log/containers` to rkt via RKT_OPTS?
I try to add `Environment=RKT_OPTS=--volume var-log-container,kind=host,source=/var/log/containers --mount volume=log,target=/var/log/containers` to the kubelet unit but i have error in the log:

    [/etc/systemd/system/kubelet.service:5] Invalid environment assignment, ignoring: RKT_OPTS=--volume var-log-container,kind=host,source=/var/log/containers    --mount volume=log,target=/var/log/containers
    ....
    Mar 28 12:39:19 az1 kubelet-wrapper[3530]: Error: invalid argument "--stage1-path=/usr/share/rkt/stage1-fly.aci" for --volume: invalid value in --volume flag "--stage1-path=/usr/s

Also I tried env to `EnviroumentFile` but nothing changed

**Comment by aaronlevy** [comment]
Can you try adding quotes:

`Environment="RKT_OPTS=..."`

**Comment by MurgaNikolay** [comment]
Thank you for your reply. 
We run kubelet without rkt due to an error https://github.com/coreos/coreos-kubernetes/issues/357
Now I can't check this but I will try after return to rkt.

**Comment by xcompass** [comment]
The above workaround works for me. Here is the complete working line:
```
Environment="RKT_OPTS=--volume container,kind=host,source=/var/log/containers,readOnly=false --mount volume=container,target=/var/log/containers"
```
Though you can't use _ in volume name. rkt doesn't like it. And I have to manually create directory ```/var/log/containers``` and ```chmod 777 /var/log/containers```. Otherwise, I got permission denied when starting kube-wrapper

**Comment by chancez** [comment]
For other folk, as @xcompass mentioned, you do need to create some directories, and additionally, no one's mentioned anything about the fluentd cursor file which gets stored in `/var/log` in the upstream kubernetes logging addon. Having the cursor files in the volume is particularly important because if fluentd restarts for any reason, the container file system containing the cursor files will go away. This means that upon starting back up, fluentd would re-ingest all log files it can find starting from the beginning again, leading to extra work, and duplicated log messages.

I'm including an example of something that should work with the upstream logging addon, however I'm not completely happy with this being the solution.

Modify your `kubelet.service` to include the following:
```
ExecStartPre=/usr/bin/mkdir -p /var/log/containers
Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log --mount volume=var-log,target=/var/log"
```

I'm not particularly fond of mounting in the entire `/var/log` directory into the container, but this container is already somewhat privileged and in upstream is run outside of a container entirely. It might be worth asking upstream to put position files in `/var/log/container-position-files` or something but this should work. I don't think you necessarily need any chmoding since it should be writable and readable by root, which system runs the rkt kubelet container as, and the kubelet itself runs as root.

**Comment by danielfm** [comment]
Just to testify that I did as @chancez explained and that fixed my problem; I was having trouble getting [cluster level logging](http://kubernetes.io/docs/getting-started-guides/logging-elasticsearch/) to work properly.

**Comment by marlinhares** [comment]
@chancez thanks for the answer. Worker for me.
CoreOs 1010.3

**Comment by AlmogBaku** [comment]
@robszumski why this settings are not configured by default?

**Comment by robszumski** [comment]
@AlmogBaku Good question, this is being addressed in https://github.com/coreos/coreos-kubernetes/issues/650. I agree with you that it should be

**Comment by chancez** [comment]
👍 to defaulting it.

**Comment by urzds** [comment]
This is broken, because `/var/log/containers` only contains symlinks to `/var/lib/docker`. I am using CoreOS CL 1235.9.0 with Kubernetes 1.5.2_coreos.2.
