### ISSUE TITLE
gitRepo volume fails, can't find git command

### ISSUE THREAD

**Issue by wstrange** [coreos/coreos-kubernetes#327]
On single node, vagrant / virtualBox,  Kube 1.1.8

Trying to mount a gitRepo volume fails. Kubernetes complains it can't find the git command.

What is odd is if I log on to the CoreOS guest - git is installed.  I am guessing the kubelet can't find git in its path?

**Comment by mischief** [comment]
@wstrange for now it might be possible to just bind mount the the relevant host paths into the kubelet rkt container.

i think this needs a lot more thought into how it will ideally work, because this affects all of the volume types that k8s supports and has a poor user experience right now. it's unlikely all of the various programs will be shipped in coreos, so the alternative is to get all of those programs into container, and figure out how to get kubelet in rkt fly to execute them.

cc @aaronlevy @pbx0

**Comment by colhom** [comment]
Just an update on this. @pbx0 and @aaronlevy are discussing whether to include `git` in the CoreOS release of the hyperkube container. Upstream does not have an opinion on whether git should be included with a hyperkube distribution-- it's an "optional" component.

**Comment by drewblas** [comment]
I ran into this exact issue and would love to see git included so that all the documented Kubernetes features are supported natively

**Comment by aaronlevy** [comment]
This has been added to the coreos-hyperkube image as of `v1.2.4_coreos.1`
