### ISSUE TITLE
aws should not need flannel port

### ISSUE THREAD

**Issue by polvi** [coreos/coreos-kubernetes#4]
VPC can do the networking we need, so we should not need to use the flannel overlay in AWS instructions.

**Comment by bcwaldon** [comment]
We need to enable pod network management in the controller-manager, then set --configure-cbr0 on the kubelets. There's a bit of a bootstrapping problem on the controller, but given that we give all pods host networking on the controller right now, it doesn't necessarily need to have an allocation on the pod network.

**Comment by eliaslevy** [comment]
See #141.

**Comment by iameli** [comment]
FWIW, part of the reason our team switched away from the first-party `kube-up` AWS cluster to this CoreOS cluster is that we were running into a number of problems relating to corner cases in VPC configuration. Nodes would intermittently come up without modifying the VPC's routing table, so they wouldn't be reachable from the rest of the network -- lots of little problems like that which would break our production cluster.

Since we switched to CoreOS and Flannel, networking has been rock solid.

It's possible my concerns have been totally addressed upstream and it'll be just as solid using VPC. Maybe it was Ubuntu's fault the whole time. I don't really have the networking expertise to say this feature is a _bad_ idea... just saw the pull request and I figured I'd share.

**Comment by aaronlevy** [comment]
I've gone back-and-forth on this myself. The cloud-provider integration sometimes feels a little spotty, and flannel generally "just works" across platforms (and also has aws-vpc integration if you still want to go that route).

Also may want to at least switch flannel to using vxlan mode in aws until a hard is made either way.

**Comment by bkeroackdsc** [comment]
flannel worries me a bit for production, having this opaque SDN layer sitting between services and the outside world (beyond all the SDN that AWS already uses). Makes it more difficult to troubleshoot network access/performance issues.

It would be nice to have VPC routing as an option.
