### ISSUE TITLE
Use HostedZone ID instead of HostedZone Name

### ISSUE THREAD

**Issue by rwillard** [coreos/coreos-kubernetes#441]
For this part of cluster.yaml when using AWS

```yaml
# The name of the hosted zone to add the externalDNSName to, 
# E.g: "google.com".  This needs to already exist, kube-aws will not create
# it for you.
hostedZone:
```

I have a public and private hosted zone with the same name, so providing the name causes the creation to ultimately fail because of it. If we instead provided Hosted Zone ID, I don't think that would be a problem

**Comment by cgag** [comment]
I went with name due to ease of use, but I didn't consider the potential ambiguity.  I'd prefer not to drop support for using the name, but we could support both by adding another field "hostedZoneID".

It looks like hostedzone id's don't have dots in them, and generally look like "Z23ABC4XYZL05B", but I can't find any docs saying we can rely on that.  If we can, we could also consider allowing you to put both ids and names into `hostedZone` and we could determine which it is.

Any thoughts @colhom?

**Comment by colhom** [comment]
I think attempting to regex the `hostedZone` field to figure out if it's an ID or name is dangerous in the long term. Let's either go with an option that doesn't require making that decision. I think `hostedZoneID`, which would be mutually exclusive with specifying `hostedZone`, is the best option.
