### ISSUE TITLE
install-kube-system is not robust to some failures

### ISSUE THREAD

**Issue by daveey** [coreos/coreos-kubernetes#447]
It looks like /opt/bin/install-kube-system got a

```
Apr 30 03:30:01 ip-10-0-5-235.ec2.internal install-kube-system[4659]: {"ErrStatus":{"metadata":{},"status":"Failure","message":"The  operation against  could not be completed at this time, please try again.","reason":"ServerTimeout","details":{},"code":500}}
```

which curl considers a success. so the cluster doesn't end up running kube-dns

**Comment by colhom** [comment]
@daveey this curl nonsense can be replaced by `kubectl` via the hyperkube container image. That will allow us to analyze exit codes meaningfully and use higher-level constructs like `kubectl apply` for this.

@daveey are you interested in doing a PR for this?

**Comment by daveey** [comment]
@colhom it actually looks like curl just needs a `-f` flag to treat a 500 as a failure. i'll submit a PR for that

**Comment by daveey** [comment]
https://github.com/coreos/coreos-kubernetes/pull/450

**Comment by colhom** [comment]
@daveey unfortunately it's not that easy. When the controller reboots, for instance, `curl -f` will return non-0 if we try to create resources that already exist, and `install-kube-system.service` will keep trying to create stuff that's already there (forever in this case).

I want to use `kubectl apply`, as that will do exactly what we want.

**Comment by daveey** [comment]
ah, that makes sense. why can't these go into /etc/kubernetes/manifests/

**Comment by colhom** [comment]
We don't want to them to be static pods.

**Comment by aaronlevy** [comment]
I'd rather not use apply on each reboot. You could stomp on user-provided changes. That being said, there's lots of room to make this smarter...

**Comment by colhom** [comment]
As to making this smarter, agree completely. We should start by using kubectl for this instead of curl.

As far as user-supplied changes- the mantra is that the cluster assets on disk are the source of truth. Given that we don't have a supported way to change cluster assets and apply them to a running cluster, that's kind of a moot point at present.

Once we can support rolling asset changes out to an existing cluster, I feel that nuking any user-supplied changes on reboot that aren't done via asset files becomes a "feature".

**Comment by daveey** [comment]
I tried using kubectl apply, but ran into https://github.com/kubernetes/kubernetes/issues/24088

**Comment by daveey** [comment]
I made https://github.com/coreos/coreos-kubernetes/pull/462 which uses a 3d party docker image with kubectl in it. What do you guys think of adding kubectl to the coreos hyperkube image until the hyperkube bug is fixed?

**Comment by aaronlevy** [comment]
> the mantra is that the cluster assets on disk are the source of truth

That should only be true for static pods: e.g. where we configure `/etc/kubernetes/manifests`

Otherwise, the objects we create using curl are simply api objects (services/replication controllers/deployments/etc), and the on-disk objects are just used during installation. Maybe someone wants to change options in the api object for dns/heapster/etc. - that is a perfectly acceptable use-case.

The fact that we run curl each reboot is partly an artifact of it being a simple solution. All of the objects *should* be running, so if someone deleted them there's likely no harm in, for example, re-creating DNS or the kube-system namespace. We've just relied on the fact that it fails if the object already exists as a simple means of being a no-op.

Ultimately the issue is that we need a way to determine actual failure vs "object already exists" failure.

If this is done with `curl`, it likely would be parsing HTTP codes (I'm assuming, not sure how the apiserver actually responds).

If this is done with `kubectl`, I believe we still have to parse output to determine this. I'm not immediately clear how this helps us (with this specific issue)

**Comment by daveey** [comment]
We could do a request to see if the resource already exists, and post it if it doesn't.
