### ISSUE TITLE
rkt: add a flag to enable rkt support

### ISSUE THREAD

**Issue by philips** [coreos/coreos-kubernetes#501]
Kubernetes v1.3 will have full rkt support; see the [rktnetes v1.3 milestone](https://github.com/kubernetes/kubernetes/milestones/rktnetes-v1.0).

We need to make this as easy to enable as the Calico support or anything else. It should just be a single configuration option on vagrant, aws, etc.

We should be able to start experimenting with this ASAP as much of the support is in k8s master. So, we should start tracking k8s v1.3 pre-releases and getting this into shape.

**Comment by Quentin-M** [comment]
Hi,

This issue just became even more important as it is a hard requirement for Stackanetes. Fully supporting OpenStack services on top of Rktnetes, following the coreos-kubernetes docs is expected by the end of July.

Right now, we can't simply swap _docker_ with _rkt_ on a Kubernetes worker node because rkt isn't available in hyperkube and thus, the kuberlet-wrapper can't run kubelet in rkt-fly. I understand that @pbx0 has started some work around that [[1]] but faced some issues with rkt (permissions) while trying to run kube-proxy [[2]]. Intel apparently suffers from the same issue since April [[3]]. It has been worked around by making it a systemd service though. I tried quickly to run the kubelet directly on CoreOS 1068, without kubelet-wrapper, but it simply won't run: breaking in the very first steps (getting rkt's version). Not exactly sure yet if the version is too old or if this is an actual bug - I am sure @yifan-gu knows.

What's the current status on this? Is there anyone working on this actively? I believe that it is quite important to get that done ASAP as it will significantly increase the user base of rktnetes and rkt - and thus, we'll get a lot more feedbacks.

It is also blocking our very first tasks on Stackanetes as it is complicated to run any k8s manifests with rktnetes. Is there any recommendation right now?

```
$ /usr/bin/kubelet \
>   --container-runtime=rkt \
>   --api-servers=https://XXX.YYY.ZZZZ.WWW \
>   --network-plugin-dir=/etc/kubernetes/cni/net.d \
>   --network-plugin= \
>   --register-node=true \
>   --allow-privileged=true \
>   --config=/etc/kubernetes/manifests \
>   --hostname-override=XXX.YYY.ZZZZ.WWW \
>   --cluster-dns=10.3.0.10 \
>   --cluster-domain=cluster.local \
>   --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
>   --tls-cert-file=/etc/kubernetes/ssl/worker.pem \
>   --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem

[...]

failed to create kubelet: failed to run [version]: exit status 2

stdout: NAME:
	version - Print the version and exit

USAGE:
	rkt version

DESCRIPTION:
	Print the version of rkt, and various build and configuration information.

GLOBAL OPTIONS:
      --debug[=false]			print out more debug information to stderr
      --dir=/var/lib/rkt		rkt data directory
      --insecure-options=none		comma-separated list of security features to disable. Allowed values: "none", "image", "tls", "ondisk", "http", "pubkey", "all"
      --local-config=/etc/rkt		local configuration directory
      --system-config=/usr/lib/rkt	system configuration directory
      --trust-keys-from-https[=false]	automatically trust gpg keys fetched from https
      --user-config=			user configuration directory

stderr: Error: unknown flag: --insecure-skip-verify
```

[1]: https://github.com/pbx0/coreos-kubernetes/commits/single-rktnetes
[2]: https://github.com/coreos/rkt/issues/2751
[3]: https://github.com/coreos/rkt/issues/2470

**Comment by pbx0** [comment]
@Quentin-M The kubelet baked into the CoreOS image is deprecated and too old to use. See:  https://groups.google.com/forum/#!topic/coreos-dev/DJeuZZeqz1s
```
$ kubelet --version=true
Kubernetes v1.1.2+1abf20d
```
I have rktnetes w/ kubelet-wrapper mostly working but still in the process of testing it and getting to the point where I can just make it a flag you set in this repo. Its definitely high-priority over here to have this before the 1.3 release. rkt 1.9 will likely be required and I still need to revisit the kube-proxy problem. Right now I also run it just as a systemd unit without rkt. 

If you can wait a few more days I can help you setup rktnetes with kubelet-wrapper. Right now you'll at minimum need this to be fixed in rkt: https://github.com/coreos/rkt/issues/2792

**Comment by Quentin-M** [comment]
@pbx0 Thank you so much for your answer and very valuable information. I'd love your help and would be glad to help you test this too! Ping me anytime (incl. weekends too).

**Comment by aaronlevy** [comment]
closed in https://github.com/coreos/coreos-kubernetes/pull/551
