### ISSUE TITLE
New stable doesn't include wrapper

### ISSUE THREAD

**Issue by bharrisau** [coreos/coreos-kubernetes#517]
I've just seen the new stable 1010.5.0 is out, but it appears the `kubelet-wrapper` has been removed.

The documentation (https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md) should be updated, at the moment it says:

> This script is currently shipping in CoreOS 962.0.0+ and will be included in all channels in the near future.

The script is currently available in Beta and Alpha. If it is never going to be available in Stable, perhaps the instructions should suggest adding it to the cloudinit?

**Comment by marineam** [comment]
The script is there in my instance of 1010.5.0:

```
CoreOS stable (1010.5.0)
core@marineam-stable ~ $ ls /usr/lib/coreos/kubelet-wrapper
/usr/lib/coreos/kubelet-wrapper
```

**Comment by robszumski** [comment]
@bharrisau You may be getting the wrapper script confused with the kubelet binary, which was removed from the stable image.

The wrapper makes it easy to run the kubelet as a rkt container, which give each user more control over which version is used and makes it easy to pass a customized flag list.

The binary was removed because you don't get any control over the version used, which doesn't follow the supported upgrade path for Kubernetes.

Going forward you can count on the wrapper script as the best way to run the kubelet.

**Comment by bharrisau** [comment]
Seems to be the source of my confusion. I didn't know there was a binary in
the Alpha and Beta.
