### ISSUE TITLE
Suggestion: make kubelet.service NOT depend on docker.service

### ISSUE THREAD

**Issue by guoshimin** [coreos/coreos-kubernetes#545]
Currently the systemd units have the following dependencies:

kubelet.service (Requires, After) docker.service (Requires, After) flanneld.service

Ref: https://github.com/coreos/coreos-kubernetes/blob/96e9d1baa781d7f1eb9e362f0c15f9a82c72b5d4/multi-node/aws/pkg/config/templates/cloud-config-worker#L22

There is a nasty failure mode where:

1. flanneld crashes
1. systemd restarts flanneld.service
1. as part of the restart process, systemd stops docker.service and kubelet.service
1. flanneld fails to come up for some reason
1. docker.service and kubelet.service marked as failed for reason 'dependency'
1. systemd restarts flanneld.service again
1. flanneld successfully comes up on second try
1. systemd does not try to start docker.service and kubelet.service

To repro, see my post on systemd-devel: https://lists.freedesktop.org/archives/systemd-devel/2016-June/036897.html

If we don't make kubelet.service depend on docker.service, kubelet wouldn't be stopped in the first place on flanneld.service restart. If kubelet itself crashes, it will always be restarted by systemd independently. If docker.service isn't running when kubelet starts, it will be started via socket activation.

**Comment by robszumski** [comment]
This is a better write up than my bug over on coreos/bugs: https://github.com/coreos/bugs/issues/1393

**Comment by cgag** [comment]
There's an issue for this bug upstream: https://github.com/systemd/systemd/issues/1312.  This seems like a viable workaround until that issue is addressed.  There's a more general workaround from stackoverflow that doesn't rely on the dependency being  being socket activated http://unix.stackexchange.com/questions/213185/restarting-systemd-service-on-dependency-failure that's good to be aware of.  With the socket activation, I think changing `Requires=` to `Wants=` should be fine.

**Comment by tomdee** [comment]
The dependency exists because Docker relies on Flannel to assigned the subnet used by the docker bridge. 

If the kubelet is configured to use CNI using --networking-plugin=cni (which is the case when useCalico=True or for the ongoing rktnetes work), then this dependency can be changed. There's no longer a need for the early docker service, and the dependency order can be changed to
`kubelet.service (Requires, After) flanneld.service (Requires, After) docker.service`

**Comment by guoshimin** [comment]
I'm not proposing to remove the docker -> flannel dependency; I agree that
flannel should be up before docker is started.

I'm proposing to remove the dependency from kubelet to docker.

**Comment by AlmogBaku** [comment]
We facing the exact same issue also:
1. flannel failed to access etcd
4. kubelet failed to restarted due dependency error

**Comment by Thermus** [comment]
I have the same issue and it prevents me from putting the cluster into production.

**Comment by aaronlevy** [comment]
It looks like this dependency was just added to the AWS installation. @colhom @cgag Is this required for some reason? IIRC in the past we've always relied on docker being socket activated.

**Comment by aaronlevy** [comment]
ping @colhom @cgag

**Comment by robszumski** [comment]
Bump. Hit this again upon upgrade to 1097.0.0.

**Comment by colhom** [comment]
I have a fix up in #563.

**Comment by colhom** [comment]
@guoshimin do you have cycles to check out the fix ( #563 ) and let me know if it's solving problems on your end.

**Comment by guoshimin** [comment]
@colhom We don't use coreos-kubernetes directly. Our setup takes ideas from a variety of places. We made the equivalent change and it served us well.

**Comment by robszumski** [comment]
I don't think https://github.com/coreos/coreos-kubernetes/pull/563 fixed this. Here's a machine on the alpha channel deployed with kube-aws v0.8.0:

Here's me SSHed into the machine, and you can see the locksmith kicks me off for an update:

```
core@ip-10-0-0-8 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1151.0.0
VERSION_ID=1151.0.0
BUILD_ID=2016-08-25-0937
PRETTY_NAME="CoreOS 1151.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

Broadcast message from locksmithd at 2016-08-29 23:56:34.531975808 +0000 UTC:
System reboot in 5 minutes!

Connection to <ec2-ip> closed by remote host.
Connection to <ec2-ip> closed.
```

From my laptop, you can see the node is back up, but not ready. This is because the kubelet isn't running:

```
szumski-mac $ kubectl get nodes
NAME                        STATUS                     AGE
ip-10-0-0-50.ec2.internal   Ready,SchedulingDisabled   10d
ip-10-0-0-8.ec2.internal    NotReady                   10d
ip-10-0-0-9.ec2.internal    Ready                      10d
szumski-mac $ ssh core@<ec2-ip>
CoreOS alpha (1153.0.0)
Last login: Tue Aug 30 00:06:39 2016 from 50.250.250.45
core@ip-10-0-0-8 ~ $ systemctl status kubelet
● kubelet.service
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Aug 30 00:04:28 ip-10-0-0-8.ec2.internal systemd[1]: Dependency failed for kubelet.service.
Aug 30 00:04:28 ip-10-0-0-8.ec2.internal systemd[1]: kubelet.service: Job kubelet.service/start failed with result 'dependency'.
```

Here's the kubelet, without the dependency on docker:

```
core@ip-10-0-0-8 ~ $ systemctl cat kubelet
# /etc/systemd/system/kubelet.service
[Service]
Environment=KUBELET_VERSION=v1.3.2_coreos.0
Environment=KUBELET_ACI=quay.io/coreos/hyperkube
Environment="RKT_OPTS=--volume dns,kind=host,source=/etc/resolv.conf --mount volume=dns,target=/etc/resolv.conf"
ExecStart=/usr/lib/coreos/kubelet-wrapper \
--api-servers=https://10.0.0.50:443 \
--network-plugin-dir=/etc/kubernetes/cni/net.d \
--network-plugin=cni \
--register-node=true \
--allow-privileged=true \
--config=/etc/kubernetes/manifests \
--cluster_dns=10.3.0.10 \
--cluster_domain=cluster.local \
--cloud-provider=aws \
--kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
--tls-cert-file=/etc/kubernetes/ssl/worker.pem \
--tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```
