### ISSUE TITLE
Possible to run kubelet-wrapper using hyperkube image provided by gcr.io

### ISSUE THREAD

**Issue by sachincab** [coreos/coreos-kubernetes#583]
Hi Team,

It looks like when Google Kubernetes project released new version, they also shipped newer version of hyperkube image.

We tried to use below hyerkube image to start kubelet-warpper for our cluster but it failed.
gcr.io/google_containers/hyperkube:v1.3.2

If we switch CoreOS hyerkube images, kubelet service successfully start using kubelet-wrapper quay.io/coreos/hyperkube:v1.3.2_coreos.0

Question: is it possible to use gcr.io/google_containers/hyperkube:v1.3.2 to start kubelet service using kubelet-wrapper on CoreOS?
This is just to align and use only one docker image to start all kubernetes components. 

quay.io/coreos/hyperkube                  v1.3.2_coreos.0        ff57fd92809b        2 days ago          440.2 MB
gcr.io/google_containers/hyperkube        v1.3.2                 d64785c49d87        4 days ago          416.3 MB

Also there is difference in sizes for hyperkube docker image provided by CoreOS and Google Kubernetes project.

Ideally we should use which docker image (quay.io/coreos/hyperkube or gcr.io/google_containers/hyperkube) to start all kubernetes components?

Please let us know your inputs on this.

Thanks!

**Sample of logs:**
------------------------------------------------------------------------------------------------
Jul 21 15:49:55 node2 kubelet-wrapper[2620]: image: using image from file /usr/lib64/rkt/stage1-images/stage1-fly.aci
Jul 21 15:49:55 node2 kubelet-wrapper[2620]: image: searching for app image gcr.io/google_containers/hyperkube
Jul 21 15:49:55 node2 kubelet-wrapper[2620]: run: discovery failed
Jul 21 15:49:55 node2 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 15:49:55 node2 systemd[1]: kubelet.service: Unit entered failed state.
Jul 21 15:49:55 node2 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jul 21 15:50:06 node2 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jul 21 15:50:06 node2 systemd[1]: Stopped kubelet.service.
Jul 21 15:50:06 node2 systemd[1]: kubelet.service: Ignoring invalid environment assignment 'FLANNEL.1_IPV4=172.21.68.0': /etc/network-environment

------------------------------------------------------------------------------------------------

Systemd unit file details for kubelet.service:
------------------------------------------------------------------------------------------------
/etc/systemd/system/kubelet.service
[Unit]
Requires=setup-network-environment.service
After=setup-network-environment.service

[Service]
**Environment=KUBELET_VERSION=v1.3.2
Environment=KUBELET_ACI=gcr.io/google_containers/hyperkube**
EnvironmentFile=/etc/network-environment
ExecStart=/usr/lib/coreos/kubelet-wrapper \
--api_servers=http://localhost:8080 \
--register-node=true \
--allow-privileged=true \
--cloud-provider=aws \
--config=/etc/kubernetes/manifests \
--hostname-override=${DEFAULT_IPV4} \
--cluster-dns=10.101.0.10 \
--cluster-domain=cluster.local \
--logtostderr=true \
--cadvisor-port=4194
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

------------------------------------------------------------------------------------------------

**Comment by pbx0** [comment]
In theory, you should be able to swap out images either from  `quay.io/coreos/hyperkube`
and `gcr.io/google_containers/hyperkube`. Our goal is to ship images as close to upstream as possible. Though, shipping our own image gives us some flexibility to ship experimental features or necessary backports specific to our setup methods.

However, currently, as you found, it will not work because the kubelet_wrapper interface actually expects the executable`/kubelet` to be present in the container's rootfs. In our distribution of hyperkube we ship a symlink `/kubelet` that points to `/hyperkube`. Any caller of the kubelet symlink will find that it works just like a kubelet binary despite using a hyperkube binary behind the scenes.

We made this decision consciously because the long-term goal of hyperkube is to have busybox style symlinks for each of its servers.  In fact, hyperkube already supports this argv[0] parsing, the symlinks are just not present upstream. This way, for components like the kubelet-wrapper, it can expect a kubelet container but accept either a kubelet or hyperkube container. Down the road it might save space to ship a kubelet only container to worker nodes and this creates a more flexible interface long-term. 

Short-term this is causing the problems you are seeing because we have not gotten the symlinks into the upstream hyperkube distribution as soon as we hoped. The issue tracking it is: https://github.com/kubernetes/kubernetes/issues/28702

I think we need to do a better job of documenting this, but, also we hope that upstream will soon include a busybox style symlinks to each of its components.

I will leave this issue open until the symlinks are present in upstream versions.

**Comment by sachincab** [comment]
Thanks for detailed information.

One question once symlink is fixed, is it possible to run as using RKT container engine?
gcr.io/google_containers/hyperkube

**Comment by pbx0** [comment]
Yes once the symlink is fixed it should be possible. You'll need a relatively new upstream version as we have just gotten fixes for rktnetes out in the latest release. Also, it will be easiest if you wait for https://github.com/coreos/coreos-kubernetes/pull/551 to be merged because then you can just configure rkt to be used by setting the `CONTAINER_RUNTIME` flag.

**Comment by sachincab** [comment]
Thanks for update and information.
I will wait for symlink to fix.  We will run the image using kubelet wrapper which by default use RKT container engine so I think it should be ok.

**Comment by pbx0** [comment]
Also, just in case I wasn't clear in the my last message: Right now we run the kubelet within a privileged rkt container, but the kubelet then uses docker to launch pods. You can switch the kubelet's runtime once https://github.com/coreos/coreos-kubernetes/pull/551 is merged, but today the kubelet itself is always run with rkt for this repo's setup methods.

**Comment by aaronlevy** [comment]
The upstream symlink fix is here: https://github.com/kubernetes/kubernetes/pull/29591 @pbx0 is also going to try and get that cherry-picked into the v1.3 releases. Once that is merged you should be able to use the upstream image. Closing issue for now.

**Comment by sachincab** [comment]
@aaronlevy, thanks for update!
It looks like merged in kubernetes master and hopefully should be available to use in upcoming kubernetes release.

**Comment by DongyiYang** [comment]
hi, may i know if the issue fixed?  I tried using  

**Environment=KUBELET_VERSION=v1.4.1**
**Environment=KUBELET_ACI=gcr.io/google_containers/hyperkube**

It still gave the same error log and kubelet service failed to start.

**Comment by pbx0** [comment]
@DongyiYang You are correct. That won't yet work because gcr.io serves docker images while quay supports transparently converting docker images to appc images for consumption by rocket.

To fix this the `KUBELET_ACI` value needs to be prefixed with `docker://` while leaving other uses of the hyperkube image set to the normal gcr.io value. This will tell rkt to fetch the docker image and convert it locally while leaving other uses of hyperkube to be run via docker like normal.  Additionally, you need to add this flag to the `RKT_OPTS` env: `--insecure-options=image`.

Sorry you ran into this, we forgot about this detail originally and just assumed things would work. Hopefully all the OCI standardization work will soon get to the point that this is all no longer necessary.  This workaround is not ideal.

To be clear, these are the exact lines I changed to get this to work for the vagrant single-node setup in this repo by editing `single-node/user-data` and then running `vagrant up`:
 
`export K8S_VER=v1.4.1`
`export HYPERKUBE_IMAGE_REPO=gcr.io/google_containers/hyperkube`
`Environment=KUBELET_ACI=docker://${HYPERKUBE_IMAGE_REPO}`
And I added this flag to the `RKT_OPTS` env variable.
`--insecure-options=image`

**Comment by DongyiYang** [comment]
@pbx0 Thank you for your quick reply. I also tried it with vagrant multiple-node setup and it is working!
