### ISSUE TITLE
kubelet run with kubelet-wrapper does not restart the docker daemon

### ISSUE THREAD

**Issue by edevil** [coreos/coreos-kubernetes#665]
When kubelet starts and has to setup the cbr0 bridge, it restarts the docker daemon [afterwards](https://github.com/kubernetes/kubernetes/blob/v1.3.2/pkg/kubelet/container_bridge.go#L59). If kubelet is being run with the kubelet-wrapper script this restart does not happen, which causes race conditions since the docker daemon can use the cbr0 bridge before it is completely configured with the correct pod CIDR.

If I run kubelet directly the restart works.

I've tried this on both CoreOS Stable and Beta.

**Comment by pbx0** [comment]
This is definitely a bug we will have to think about since calling the restart command inside a container gives the following:
```
/# systemctl restart docker
Running in chroot, ignoring request.
```
The likely work-around will be to bind-mount a bash script in place of the container's systemctl command that escapes the chroot via:
```
#!/bin/sh
exec nsenter -m -u -i -n -p -t 1 -- /bin/systemctl "$@"
```
The bash script would live on the host. [This workaround](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/pkg/config/templates/cloud-config-controller#L210) has been used previously (as a temporary workaround) for calling out to rkt from inside the container as well. I'll make a PR to coreos-kubernetes if you try this workaround in the meantime let me know how it goes.

**Comment by pbx0** [comment]
Closing this since there is both a workaround and long-term solution. Please re-open if any of this doesn't work.

**Comment by edevil** [comment]
Didn't notice the edit... I'm going to go with the Kubenet plugin. Thanks.

**Comment by pbx0** [comment]
@edevil One thing to note, if you are using flannel as an overlay network, `kubenet` will not work and you must use cni. See this commit as an example of how we configure flannel and cni: https://github.com/coreos/coreos-kubernetes/pull/551/commits/7ad134744b75d0a8a75af165afeb107ea245f87a

**Comment by edevil** [comment]
Thanks, but I'm not using flannel. I'm using cbr0 with Azure routes.
