### ISSUE TITLE
Error: failed to compress TLS assets: NotFoundException: Invalid arn

### ISSUE THREAD

**Issue by enxebre** [coreos/coreos-kubernetes#688]
Following steps here https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html
I got:

```
Error: failed to compress TLS assets: NotFoundException: Invalid arn
	status code: 400, request id: 
```
kube-aws version v0.8.2

**Comment by robszumski** [comment]
Aplogies for the dumb questions, but:

 - Did you [create the KMS key](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html#kms-key)? 
 - Since this is a 4xx error, did you create it in the correct region?
 - Did you swap out the ARN code [in this section](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html#initialize-an-asset-directory)?

**Comment by enxebre** [comment]
I got back to this today and got it working, not sure was the problem was. Thanks
