### ISSUE TITLE
CoreOS + Kubernetes Step By Step: DNS addon is broken

### ISSUE THREAD

**Issue by stephen144** [coreos/coreos-kubernetes#720]
Step 5 of the CoreOS + Kubernetes Step By Step guide, is incomplete. The DNS addon created there cannot connect to the API server because it is missing TLS config. See [this](https://github.com/kubernetes/kubernetes/issues/32480) Kubernetes issue. I was able to get DNS working by following [this](https://github.com/kubernetes/kubernetes/issues/32480#issuecomment-249889480) comment in the linked issue. It seems that the kubeDNS pod should be using a `kubeconfig` file.

API server log shows a lot of:

> Unable to authenticate the request due to an error: crypto/rsa: verification error

While the kubeDNS log is filled with:

> reflector.go:136] Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
> reflector.go:136] Failed to list *api.Endpoints: the server has asked for the client to provide credentials (get endpoints)

**Comment by pbx0** [comment]
While this definitely should be fixed -- I strongly encourage people to avoid using the Step By Step guide except as a learning exercise. Otherwise it can be tedious, error prone, and tends to lack the validation that our setup scripts receive.

I encourage people instead to either try using the multi-node or single-node via vagrant, use kube-aws, or to use the multi-node/generic scripts.

**Comment by rdtr** [comment]
Yeah we use k8s on production (on AWS) and followed the step-by-step guide because at that point I could find no clear way to deploy a whole cluster onto a private network, which is our company's requirement. I believe it's still the case as of today.

But for the sections of "Deploy Kubernetes Master Node(s)" and "Deploy Kubernetes Worker Node(s)", we utilize multi-node/generic scripts because it does every steps we need and it's maintained well (really appreciated it).
So far there is no problem about kubeDNS.

**Comment by stephen144** [comment]
Good to know y'all. I was doing the step-by-step as a learning exercise. In that it served it's purpose. As for the issue, I probably messed something up. Should I close this?

**Comment by pbx0** [comment]
@rdtr -- Glad that it is working well for you and thank you for explaining your use case. Don't hesitate to file an issue should you find anything wrong.

@stephen144 I think this is fine to leave open until it gets fixed. We do want to fix the guide, I just wanted people to know that if step-by-step is giving you trouble there are easier and less error prone routes to take.

**Comment by ElijahCaine** [comment]
@pbx0 I'd love to get this resolved (whatever 'resolved' looks like) in #722, What do you think would best achieve that? Adding a warning about doing a manual setup?  Config examples?  Point me in the right direction and I'll try to write it up.
