### ISSUE TITLE
Gpg2 verifying Signature

### ISSUE THREAD

**Issue by kenwan12** [coreos/coreos-kubernetes#746]
I got something like below following the steps to verify the 2 latest releases -

$ gpg2 --verify kube-aws-${PLATFORM}.tar.gz.sig kube-aws-${PLATFORM}.tar.gz
gpg: Signature made Thu Sep 22 22:14:47 2016 BST using RSA key ID BEDDBA18
gpg: Good signature from "CoreOS Application Signing Key <security@coreos.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 18AD 5014 C99E F7E3 BA5F  6CE9 50BD D3E0 FC8A 365E
     Subkey fingerprint: 55DB DA91 BBE1 849E A27F  E733 A6F7 1EE5 BEDD BA18
$

Is there any concern ?

Thanks

Ken

**Comment by dghubble** [comment]
Remember, openpgp/gpg verify let you verify the tarball was signed by the CoreOS Application Signing subkey, which is why you see:

```
gpg: Good signature from "CoreOS Application Signing Key security@coreos.com" [unknown]
```

Whether or not you consider that key "trusted" is up to you and your local keychain. You've left its trust level set to "unknown" so indeed, its "not certified with a trusted (by you) signature".

You may choose to trust signatures from our key by editing your trust level, after cross referencing with the posted [application key](https://coreos.com/security/app-signing-key/), public keyservers, or others you trust.

```
gpg2 --edit-key 18AD5014C99EF7E3BA5F6CE950BDD3E0FC8A365E
trust
quit
```
