### ISSUE TITLE
Provide a Cloudformation Template for AWS

### ISSUE THREAD

**Issue by wolfeidau** [coreos/coreos-kubernetes#79]
It looks like there are some plans to support AWS, I am planning on building a cloudformation template for my own setup.

Are you interested in accepting this as pull request?

**Comment by hunter** [comment]
We're working on something similar so would be good to have something standard.

From looking through the repo history there were CF templates at some point. Was there a reason for removing them?

**Comment by polvi** [comment]
We are actively working on a CloudFormation. Our plan is to start with a single node master that has mechanics to keep the master alive. We are starting with this because:

1) It will be minimal cost to try out
2) master failure does not kill the cluster, just stops scheduling
3) Google Container Engine is single master, so we feel that is a decent baseline to track

We intend to put this CloudFormation into CoreOS, Inc, production. From there we will evaluate more complex setups. If you have a particular setup you would like to see, we would happily take your PR or work with you to create something that works. 

What architecture were you planning on creating in the CloudFormation?

**Comment by hunter** [comment]
For us it's just a simple dev environment. A single master with 2-3 nodes.

**Comment by silas** [comment]
See #80 (rendered template is here https://coreos-kubernetes.s3.amazonaws.com/latest/template.json)

**Comment by polvi** [comment]
@wolfeidau @hunter would love your feedback on

**Comment by hunter** [comment]
Nice! Looks like a few improvements over one we'd hacked together. We're using spot instances for the workers but probably not something everyone would want to run.

The first thing that jumps out at me is, can the API Server URL be determined by the `kube-aws-controller` host's IP Attribute?

**Comment by bcwaldon** [comment]
@hunter just landed it, please take a look in master. To answer your specific question, we currently hard-code the controller IP to 10.0.0.50, so no discovery intra-cluster is necessary. There are clear improvements to this, but it's a good starting point!

**Comment by wolfeidau** [comment]
This is great news, I will most certainly be using it as a basis for the work I am doing.

I have been building up a cloudformation "layer cake", while following the segregation of the etcd, workers and controllers. 

Main idea is to lay down the VPC, with public/private subnets, then add each component, such as etcd, workers and controllers on as a separate cloudformations. This makes it much easier to maintain and upgrade them.

see http://awsadvent.tumblr.com/post/38685647817/strategies-reusable-cfn-templates

Definitely going to dig into this template.

**Comment by wolfeidau** [comment]
I have had a look at `kube-aws` tool which is now a part of this project, pretty amazing work will be pretty easy to extend it for what I want to create.

I had never considered using golang to `render` the aws cloudformation, but given all the things which need to be injected it makes a lot of sense.

**Comment by bcwaldon** [comment]
@wolfeidau I swore off building CloudFormation templates by hand a while ago :)
