### ISSUE TITLE
Question about IPs in setup

### ISSUE THREAD

**Issue by qrpike** [coreos/coreos-kubernetes#798]
I have been following the documentation on getting kubernetes setup on a bare metal cluster of CoreOS machines.

My question is about the IPs in the docs, just for reference I have 3 networks in my cluster:
Networks:
- Public network ( external, public IPs ) 1gb. DHCP. 66.x.x.x
- Management / Internal network. 10gbps. DHCP. 10.10.1.0/24
- Storage network. 10gbps. DHCP. 10.10.2.0/24

I wish for flannel to run over the management 10g network, however actual traffic will come in through the public network. I'm not trying to do anything strange, just not completely clear what IPs should be set. Public IP or the Management network IP... eg: ${ADVERTISE_IP} should be the actual public 66.x IP? 

Thank you!

**Comment by aaronlevy** [comment]
Hi @qrpike 

The `ADVERTISE_IP` gets used for a few things in our guide:

* How the api-server will announce its network addressability to other components in the cluster. 
* How we document creating TLS certificate CN/SAN entries.
* How nodes identify themselves to the cluster (and for api-server<-->node traffic)
* The interface flannel uses for podnetwork traffic

It is a simplification, because it assumes the ADVERTISE_IP  is routable between nodes (for pod traffic and inter-component traffic), but also publicly routable (so a user with `kubectl` can access the api-server).

But in your case you should be able to have flannel and inter-component traffic use the internal network, and then have api-server bind on all interfaces (if you do need to reach it from external network).

For flannel traffic to use your management network, you can set the `FLANNELD_IFACE` option to the management interface by name, or the ip address assigned to that interface. 

For nodes `--hostname-override` you can use the internal network as well (as long as it's routable to your api-server).

For api-server `--advertise-address` you can also use internal network (this is for component to component communication)

Then for external traffic most entry points will be via the kube-proxy (usually listen on all interfaces), or for interacting with api-server can listen on all interfaces (just make sure that your TLS certificate CN/SANs reflect how you will be reaching the api-server - e.g. both by internal network ip and external ip/hostname).

Hope that helps

**Comment by qrpike** [comment]
@aaronlevy Thanks for the help, I have gotten it all setup. However some of the ports in the tutorial I had to correct. Mainly the worker node needed --api-service=https://${master_ip}. Kept trying to use port 80, however needed to force it to use https(443).

Thanks,
