### ISSUE TITLE
Failed to apply cloud-config: Unable to decode / pb with SSL certs

### ISSUE THREAD

**Issue by lucmichalski** [coreos/coreos-kubernetes#88]
Template not working

Failed to apply cloud-config: Unable to decode /etc/kubernetes/ssl/ca.pem (Unable to decode base64: "illegal base64 data at input byte 64")

I provide it through the AWS form

**Comment by robszumski** [comment]
I also had this issue when using just the CloudFormation button.

**Comment by rclayton-the-terrible** [comment]
Same above.  Successfully launched via form, but the controller instance failed on cloud-config.

**Comment by lucmichalski** [comment]
I used successfully the following commands:

$ ./kube-aws render --output=artifacts/template.json
You can change the template.json in order to fit some custom requirements for your cluster
$ aws s3 cp --recursive --acl=public-read artifacts/ s3://<bucket>/
$ ./kube-aws up --aws-debug=true (Debug optional)
Be sure to have the cross-loaded files readable:

Only problem I have is that I cannot get kube-proxy displaying me the Kube-UI or Cluster-Monitoring addons on a public IP. Maybe a couple of more service accounts with different credentials would be required. Any help from the coreos team would be welcomed :-). (It seems that they removed the Kube-UI addons for some reason)

**Comment by aaronlevy** [comment]
@lucmichalski the only addon that is currently deployed is the DNS addon. This is because it is essentially a requirement of a functioning cluster. The initial goal of these tools are to stand up a fully-functioning cluster into which you can install kubernetes applications (other addons included).

The UI addon can be deployed like any other application into your cluster (via `kubectl create -f`): http://kubernetes.io/v1.0/docs/user-guide/ui.html

**Comment by aaronlevy** [comment]
I was able to launch a cluster via the cloudconfig button. I encoded my TLS assets via:

`> base64 certname.pem`

If launching a cluster via the CloudConfig button is still an issue, please feel free to re-open this issue.
